name: works

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: setup env file
        run: |
          touch .env
          echo "SWITCHBOT_TOKEN=${{ secrets.SWITCHBOT_TOKEN }}" >> .env
          echo "WEATHEROPENMAP_APP_KEY=${{ secrets.WEATHEROPENMAP_APP_KEY }}" >> .env
          echo "JMA_WEATHER_CODE=${{ secrets.JMA_WEATHER_CODE }}" >> .env

      - name: Test
        run: npm run test:coverage

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
